// Sunday messages from Pastor R.T. Owoseni and guest ministers at C.A.C Salvation
// Centre, Ilorin — transcribed from the district's WhatsApp broadcast notes. One
// entry per week (skips weeks with no note posted to the group); minor spelling/
// punctuation clean-up only, content is otherwise verbatim.
//
// podcastUrl: matched by hand against Pastor Owoseni's Spotify podcast
// (open.spotify.com/show/2VBBGHUo6nMITGmGGrEUoM) — episode descriptions there
// reuse the same MINISTER/TOPIC/TEXT/NOTES text, or the scripture references
// match exactly, so only set this when that overlap confirmed the episode is
// the same message (uploaded days-to-weeks after the WhatsApp note, hence the
// date drift). The show is Pastor Owoseni's own, so guest-minister messages
// and a few of his own with no confirmed match are left unset — don't guess.
//
// applePodcastUrl: same show, same method, matched independently against
// Pastor Owoseni's Apple Podcasts feed ("CAC Salvation Centre - Ilorin",
// podcasts.apple.com/us/podcast/id1872275390). Apple and Spotify don't always
// carry the same episodes, so the two fields aren't set on exactly the same
// entries.

export interface IlorinSermon {
  slug: string;
  dateIso: string;
  date: string;
  minister: string;
  theme?: string;
  topic: string;
  texts: string;
  excerpt: string;
  body: string[];
  podcastUrl?: string;
  applePodcastUrl?: string;
}

export const ILORIN_SERMONS: IlorinSermon[] = [
  {
    slug: "2026-01-18-your-benefits-as-a-sheep-under-a-shepherd",
    dateIso: "2026-01-18",
    date: "January 18, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Your Benefits as a Sheep Under a Shepherd",
    texts: "Psalms 23:1–6; Psalm 32:8",
    podcastUrl: "https://open.spotify.com/episode/4Wi7JFFDpYwtXifTCAqwSM",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/benefits-of-a-sheep-under-a-shepherd-part-2/id1872275390?i=1000746793950",
    excerpt: "God expects us to see ourselves as sheep under Him, not goats. Being a sheep has many benefits that cannot be exhausted.",
    body: [
      "God expects us to see ourselves as sheep under Him, not goats. Being a sheep has many benefits that cannot be exhausted.",
      "BENEFITS OF BEING A SHEEP",
      "Divine Guidance (Psalm 23:3). One of the duties of a shepherd is to guide the sheep, and the sheep is meant to rely on the shepherd for guidance. As children of God, God wants us to rely on Him for guidance.",
      "God’s guidance can be in any form. It can be in the form of an idea.",
      "You can only benefit from God’s divine guidance if you have a good relationship with the Holy Spirit. If one does not live a holy life, he cannot enjoy divine guidance from God.",
      "Divine Protection (Psalm 23:4). As a sheep under a shepherd, the sheep is helpless and has to depend on the shepherd for protection. As children of God, God expects us to depend on Him for protection. A man cannot protect himself; he has to depend on the only source of protection, which is God.",
    ],
  },
  {
    slug: "2026-01-25-your-benefits-as-a-sheep-under-a-shepherd",
    dateIso: "2026-01-25",
    date: "January 25, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Your Benefits as a Sheep Under a Shepherd",
    texts: "Psalm 23:5",
    podcastUrl: "https://open.spotify.com/episode/6IhroSNM2CzTY7WtePTlYv",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/benefits-as-a-sheep-under-a-shepherd-part-3/id1872275390?i=1000746794028",
    excerpt: "One of the benefits of being a sheep under a Shepherd is ENVIABLE PROVISION. When God speaks, He does not speak to only a particular set of people;…",
    body: [
      "One of the benefits of being a sheep under a Shepherd is ENVIABLE PROVISION. When God speaks, He does not speak to only a particular set of people; the Word of God is for everyone. The Word of God you believe is the one that will work for you (John 1:4). We are meant to act as sheep, not goats. As a sheep, what God expects you to do is to FOLLOW. God deserves to be feared. Following God might seem foolish, but it is the best thing to do.",
    ],
  },
  {
    slug: "2026-02-01-why-thanksgiving",
    dateIso: "2026-02-01",
    date: "February 1, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Why Thanksgiving?",
    texts: "Malachi 2:1; Luke 17:13–19",
    podcastUrl: "https://open.spotify.com/episode/62X00xs2s2AIxL2bnxcwEJ",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/why-thanksgiving/id1872275390?i=1000747733124",
    excerpt: "There is always a reason for everything God says in His Word. That reason is the key behind the fulfilment of that Word.",
    body: [
      "There is always a reason for everything God says in His Word. That reason is the key behind the fulfilment of that Word.",
      "Whatever is done unto the Lord must be done with understanding. God treats us the way we treat Him.",
      "WHY THANKSGIVING",
      "Thanksgiving preserves our blessings. When God blesses us, the way to preserve that blessing is through thanksgiving. Only God has the capacity to preserve blessings (Malachi 2:1). Thanksgiving is a preservative that keeps your blessing from being destroyed.",
      "Thanksgiving perfects our blessings. Whatever God gives is just a fraction, and only thanksgiving can bring perfection (Luke 17:13–19). Whatever is not perfected cannot stand the test of time and can be destroyed by the devil. That is why we need to give thanks to God.",
    ],
  },
  {
    slug: "2026-02-08-growing-in-favour",
    dateIso: "2026-02-08",
    date: "February 8, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Growing in Favour",
    texts: "Luke 2:52, 1 Corinthians 15:58",
    podcastUrl: "https://open.spotify.com/episode/0H3WNyTfk7sGX7VnFh2lgW",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/growing-in-favour/id1872275390?i=1000748780121",
    excerpt: "GROWTH is an evidence of life; where there's no life, DEATH will set in.",
    body: [
      "GROWTH is an evidence of life; where there's no life, DEATH will set in.",
      "As children of God, we ought to grow in FAVOUR. If we don't grow in FAVOUR, frustration sets in; growth in FAVOUR brings about spiritual stability.",
      "To be fruitful in all areas of our life, we have to grow in FAVOUR.",
      "HOW DO I GROW IN FAVOUR",
      "Deepen your relationship with God.",
      "God expects us to have a deep relationship with Him; the deeper you go in God, the deeper you go in His FAVOUR.",
      "God will never withdraw His FAVOUR from you if you have a deep relationship with Him (1 Corinthians 15:58).",
      "Don't be a shallow Christian; have a very good relationship with God.",
    ],
  },
  {
    slug: "2026-02-15-growing-in-favour",
    dateIso: "2026-02-15",
    date: "February 15, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Growing in Favour",
    texts: "John 15:4-5",
    excerpt: "Anybody without Jesus has not obtained divine favour and is also not part of God's family.",
    body: [
      "Anybody without Jesus has not obtained divine favour and is also not part of God's family.",
      "HOW DO I GROW IN FAVOUR?",
      "Stay connected to the Source of favour.",
      "Jesus is the Source of favour.",
      "Anyone who disconnects from the Source of favour will experience the dryness of favour (John 15:4-5).",
      "As Christians, when we remain connected to the Source of favour which is Jesus our lives must portray Christ in everything we do.",
      "As children of God, we ought to grow in favour. If we do not, frustration sets in.",
      "Live in righteousness (Psalm 5:12)",
      "The blessings of the righteous come directly from God.",
      "To grow in favour, we are meant to live in righteousness and not in sin.",
    ],
  },
  {
    slug: "2026-03-01-jesus-our-burden-bearer",
    dateIso: "2026-03-01",
    date: "March 1, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Jesus Our Burden Bearer",
    texts: "Isaiah 53:3–5; Psalm 103:14–15; Ecclesiastes 10:15; Proverbs 18:10; Psalm 55:22; 1 Peter 5:7",
    podcastUrl: "https://open.spotify.com/episode/3Km5PczTsRQH3WCYSwF9Om",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/jesus-our-burden-bearer-1/id1872275390?i=1000752320746",
    excerpt: "One of the benefits of redemption is that Christ is our Burden Bearer — and what you know about Jesus determines what you receive from Him.",
    body: [
      "One of the benefits of redemption is that Christ is our Burden Bearer — and what you know about Jesus determines what you receive from Him. Many Christians relate to God only as their Savior and stop there, without realizing He is also the One who carries what they were never meant to carry alone. The work of Jesus goes far beyond rescuing us from hell; it reaches into the daily weight of living.",
      "By nature, man was not designed to bear the burdens of this world (Psalm 103:14–15). Life is full of burdens the devil delights in loading onto us — burdens of fear, of care, of things far beyond our strength. Carrying them alone was never the plan for a child of God.",
      "That is why wise people consciously and deliberately cast their burdens on Jesus, rather than carrying them alone. It is a decision, not just a feeling — a deliberate, repeated act of putting the weight down at His feet.",
      "Jesus cares for you. Whatever you are carrying today, He is not only able to save you — He is able to bear it.",
    ],
  },
  {
    slug: "2026-03-08-embracing-the-promises-of-god",
    dateIso: "2026-03-08",
    date: "March 8, 2026",
    minister: "Evangelist Femi Adebayo",
    topic: "Embracing the Promises of God",
    texts: "Hebrews 6:12, Nehemiah 9:21, 2 Kings 5:11, Romans 4:18",
    excerpt: "The promises of God have the power to transform lives.",
    body: [
      "The promises of God have the power to transform lives.",
      "When you do not embrace the promises of God, you will not benefit from them.",
      "REASONS PEOPLE FAIL TO EMBRACE GOD'S PROMISES",
      "Many people always expect a particular approach from God, but God works in many ways. (2 Kings 5:11)",
      "Sometimes the promises of God do not reflect what people are currently going through. (Romans 4:18)",
      "Therefore, you need patience and faith to enjoy the promises of God.",
    ],
  },
  {
    slug: "2026-03-15-laying-foundation-for-god-s-blessing",
    dateIso: "2026-03-15",
    date: "March 15, 2026",
    minister: "Pastor D.O.B. Osundeyi",
    topic: "Laying Foundation for God's Blessing",
    texts: "Psalm 104:5-6, Psalm 1:1, Proverbs 1:10",
    excerpt: "Being blessed connotes being favored by God.",
    body: [
      "Being blessed connotes being favored by God.",
      "Whoever wants to enjoy God's blessings must not walk in the counsel of the ungodly.",
      "Do not associate with ungodly people; walk with the right people (Psalm 1:1). Be careful of the company you keep: \"Bad company corrupts good character\" (1 Corinthians 15:33).",
    ],
  },
  {
    slug: "2026-03-22-power-to-move-forward",
    dateIso: "2026-03-22",
    date: "March 22, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Power to Move Forward",
    texts: "Exodus 14:14–18",
    podcastUrl: "https://open.spotify.com/episode/3zFDWHiAimfqLCynbevlq4",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/power-to-move-forward/id1872275390?i=1000756582150",
    excerpt: "One of the favours we must enjoy as children of God is the power to move forward.",
    body: [
      "One of the favours we must enjoy as children of God is the power to move forward.",
      "Our God is a forward-moving God (a progressive God).",
      "We are created in the image of God, and as His children, He wants us to move forward.",
      "God cannot be stranded.",
      "Whatever you are going through, always remember that if God cannot be stranded, you cannot be stranded.",
      "God cannot be stagnated.",
      "God cannot be stopped.",
      "As long as you are a child of God, no power can stop you (Exodus 14:14–15).",
      "As children of God, He expects us to resemble Him in everything. As long as God cannot be stopped, we cannot be stopped.",
    ],
  },
  {
    slug: "2026-03-29-tied-down-for-his-glory",
    dateIso: "2026-03-29",
    date: "March 29, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Tied Down for His Glory",
    texts: "Mark 11:2, 8; Daniel 2:21; Psalm 31:15",
    podcastUrl: "https://open.spotify.com/episode/5mKMPPzDQjEPqMcQf5oDkY",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/tied-down-for-his-glory/id1872275390?i=1000758116101",
    excerpt: "God has a reason for everything He does.",
    body: [
      "God has a reason for everything He does.",
      "For a child of God, not all restrictions, disappointments, or delays are demonic.",
      "God controls times and seasons (Daniel 2:21; Psalm 31:15).",
      "Your delay or restriction is for a while, not for life.",
      "Divine delay leads to the manifestation of glory.",
      "There is nothing God delays in your life that will not be restored.",
    ],
  },
  {
    slug: "2026-04-05-resurrection-power",
    dateIso: "2026-04-05",
    date: "April 5, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Resurrection Power",
    texts: "Matthew 28:2-7, Romans 8:11",
    podcastUrl: "https://open.spotify.com/episode/10roEqjP5eAdX2Cr0rRmzg",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/resurrection-power/id1872275390?i=1000759379788",
    excerpt: "There are many powers on earth, but the only power that has challenged and defeated the power of death is the Resurrection Power.",
    body: [
      "There are many powers on earth, but the only power that has challenged and defeated the power of death is the Resurrection Power.",
      "One of the major things that differentiates Christians from others is the Resurrection Power.",
      "The Resurrection Power is the power that raises up. Whatever might be going down in any aspect of your life, the Resurrection Power is more than enough to raise it up.",
      "It is a life-giving power. The Resurrection Power has the ability to give life to anything that is dead.",
      "It is a way-making power. When the Resurrection Power is at work, nothing can hinder it, because it is a way-making power.",
      "It is a level-changing power.",
      "It is a mortal-body-quickening power (Romans 8:11).",
    ],
  },
  {
    slug: "2026-04-12-understanding-the-levels-of-the-meaning-of-the-word-god",
    dateIso: "2026-04-12",
    date: "April 12, 2026",
    minister: "Pastor D.O.B. Osundeyi",
    topic: "Understanding the Levels of the Meaning of the Word God",
    texts: "John 1:1; 2 Timothy 3:16; Genesis 1:3; Mark 4:35–41",
    excerpt: "The word of God is beyond the letters that we see",
    body: [
      "The word of God is beyond the letters that we see",
      "The word of God is powerful",
      "The word of God is mystery and it can only be understood through the help of the holy Spirit",
      "The word of God is God himself (John 1:1)",
      "The word of God has power to create (Genesis 1:3)",
      "The word of God brings peace and calm",
    ],
  },
  {
    slug: "2026-05-03-you-and-your-character",
    dateIso: "2026-05-03",
    date: "May 3, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "You and Your Character",
    texts: "1 Peter 3:2-4",
    excerpt: "Your character plays a vital role in you enjoying the Divine Favour.",
    body: [
      "Your character plays a vital role in you enjoying the Divine Favour.",
      "You can enjoy blessings, Mercy and Favour from God and loose it based on your character.",
      "WHAT IS CHARACTER?",
      "Character is what you have within.",
      "Character is your hidden nature.",
      "Character is what you exhibit when you are under pressure (Being under pressure is a way God tests believers to see how they perform).",
      "Your true beauty is not in your physique, but it's in your character.",
      "You need to work on your character to enjoy God's Favour.",
      "You can be filled with the holy Spirit and have a bad character.",
      "Don't place value on gifts at the expense of building a good character.",
    ],
  },
  {
    slug: "2026-05-10-understanding-the-god-of-favour",
    dateIso: "2026-05-10",
    date: "May 10, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Understanding the God of Favour",
    texts: "Genesis 37",
    podcastUrl: "https://open.spotify.com/episode/700kNebQgwGrCoq5mE6i3h",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/understanding-the-god-of-favour/id1872275390?i=1000767078390",
    excerpt: "If you do not understand God, you may walk away from the very favour He has for you. Joseph is proof of what patience looks like on the other side of that understanding.",
    body: [
      "If you do not understand God, you may walk away from the very favour He has for you. Understanding positions you to receive it — and no matter what you are going through right now, His favour is still available. You only need to understand Him, and position yourself to receive it.",
      "Joseph is proof of that. Before he ever wore a Prime Minister's robes, he was hated by his own brothers, then envied, then conspired against (Genesis 37:17–18). He was stripped naked, thrown into a deep pit, and sold into slavery — twice. He was falsely accused, unjustly imprisoned, and then forgotten by the very man he had helped, left to wait in a cell while his case went unspoken for.",
      "None of it stopped what God had for him. In spite of all these challenges, Joseph became the Prime Minister.",
      "The journey to enjoying God's favour is not always easy. Challenges will come your way — but you must remain patient. Joseph did, and in the end, he stood in the very place God had always intended for him.",
    ],
  },
  {
    slug: "2026-05-17-a-citizen-of-a-country-in-another-country",
    dateIso: "2026-05-17",
    date: "May 17, 2026",
    minister: "Pastor Dr. H.O. Ilufoye",
    topic: "A Citizen of a Country in Another Country",
    texts: "2 Tim. 3:1-3, Col. 1:9-10",
    excerpt: "As a Christian, your philosophy, reasoning, thinking, and way of acting should not be like that of the world.",
    body: [
      "As a Christian, your philosophy, reasoning, thinking, and way of acting should not be like that of the world.",
      "The values of the world system and its measure of success are not the same as those of Heaven.",
      "It takes discipline to make it to Heaven.",
      "Don't trade anything for eternity with Christ.",
    ],
  },
  {
    slug: "2026-05-24-gate-of-faith",
    dateIso: "2026-05-24",
    date: "May 24, 2026",
    minister: "Pastor R.T. Owoseni",
    theme: "Gates of Favour",
    topic: "Gate of Faith",
    texts: "Hebrews 11:1–6",
    podcastUrl: "https://open.spotify.com/episode/0gkrE1ClrsvUrruZVM1GiM",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/gates-of-favour-by-faith-pt1/id1872275390?i=1000769413063",
    excerpt: "Faith is the currency of Heaven; without it, you can't make any transactions with Heaven.",
    body: [
      "Faith is the currency of Heaven; without it, you can't make any transactions with Heaven.",
      "Faith has nothing to do with your age or status.",
      "The devil doesn't want you to have faith, so he introduces fear and doubt.",
      "Faith makes one's life attractive to God. To attract God's favour, your life has to be attractive to God.",
      "You can only live by faith. Faith determines your existence. (Habakkuk 2:4, Hebrews 10:38)",
      "The level of your faith determines the level of your exploits.",
    ],
  },
  {
    slug: "2026-05-31-thanking-god-by-faith",
    dateIso: "2026-05-31",
    date: "May 31, 2026",
    minister: "Pastor R.T. Owoseni",
    theme: "Gates of Favour",
    topic: "Thanking God by Faith",
    texts: "2 Chronicles 20:1–6",
    podcastUrl: "https://open.spotify.com/episode/0up83JZUoGrDhuqyLEn426",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/thanking-god-by-faith/id1872275390?i=1000770511099",
    excerpt: "There are many ways in which we can relate with God, and one of them is through thanksgiving.",
    body: [
      "There are many ways in which we can relate with God, and one of them is through thanksgiving.",
      "Another dimension of thanksgiving is thanksgiving by faith.",
      "Your thanksgiving to God should not depend on whether He blesses you or not.",
      "There are battles that have been won in the spirit realm, but it takes thanksgiving by faith to access the victory.",
      "Thanking God in advance is like poison to the devil.",
      "Learn to thank God for who He is.",
    ],
  },
  {
    slug: "2026-06-07-growing-in-faith",
    dateIso: "2026-06-07",
    date: "June 7, 2026",
    minister: "Pastor R.T. Owoseni",
    theme: "Gates of Favour",
    topic: "Growing in Faith",
    texts: "Matthew 14:24–32; Hebrews 11:33",
    podcastUrl: "https://open.spotify.com/episode/5woQm4NCKPJvnCrJ340hX3",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/growing-in-faith/id1872275390?i=1000771596766",
    excerpt: "Faith is like a seed (a spiritual seed). For a seed to grow, it must be nurtured.",
    body: [
      "Faith is like a seed (a spiritual seed). For a seed to grow, it must be nurtured.",
      "One of the ways to enjoy divine favour from God is by growing in faith.",
      "In the Christian journey, there are waters we need to walk on, and we can only walk on them by faith.",
      "HOW DO I GROW IN FAITH?",
      "By regularly reading the Word of God (1 Peter 2:2).",
      "By meditating on the Word of God regularly (Joshua 1:8).",
      "By being positive in all your confessions.",
      "By always looking unto Jesus (Hebrews 12:2).",
    ],
  },
  {
    slug: "2026-06-21-obtaining-god-s-promises-by-faith",
    dateIso: "2026-06-21",
    date: "June 21, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Obtaining God's Promises by Faith",
    texts: "Hebrews 11:33",
    podcastUrl: "https://open.spotify.com/episode/5Fhlc8OAUBo3lgpM5QkIgq",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/obtaining-gods-promises-by-faith/id1872275390?i=1000773608866",
    excerpt: "Whatever affects your faith affects your relationship with God.",
    body: [
      "Whatever affects your faith affects your relationship with God.",
      "One of the major differences between Christianity and other religions is faith in God.",
      "What makes you a believer is faith in Christ.",
      "Don't compromise your faith for anything.",
      "Faith gives strength for the Christian journey. Man can only run the race of life by divine strength. Without God's divine strength, you become stranded, seeking help elsewhere.",
      "Faith restores lost virtues (Hebrews 11:11-12).",
      "As long as you hold on to your faith in Him, there will always be life.",
    ],
  },
  {
    slug: "2026-06-28-how-to-activate-god-s-blessings-through-praise-and-worship",
    dateIso: "2026-06-28",
    date: "June 28, 2026",
    minister: "Elder Ogunjobi",
    topic: "How to Activate God's Blessings Through Praise and Worship",
    texts: "Ecclesiastes 3:6, James 1:2, Psalm 15:1-5",
    excerpt: "No matter the situation, always thank God.",
    body: [
      "No matter the situation, always thank God.",
      "Invest your time in doing the will of God.",
      "Those who can access God's blessings through worship are those who are righteous (Psalm 15:1-2).",
      "God only rewards a pure heart.",
      "To be able to worship and praise God well, you have to completely get rid of every form of evil.",
    ],
  },
  {
    slug: "2026-07-05-attracting-great-mercy",
    dateIso: "2026-07-05",
    date: "July 5, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Attracting Great Mercy",
    texts: "Luke 1:57–58",
    podcastUrl: "https://open.spotify.com/episode/0jHY9hoAM8bkw4NdXWKYxD",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/attracting-great-mercy-pt2/id1872275390?i=1000775555791",
    excerpt: "God can show an individual great mercy without the individual's input.",
    body: [
      "God can show an individual great mercy without the individual's input.",
      "God's mercy is available to everyone, but as believers, we are expected to know how to attract His great mercy.",
      "When we play our part in attracting God's great mercy, God will also play His part by granting us His great mercy.",
      "One of the ways to attract God's great mercy is by serving Him selflessly and sacrificially.",
      "Serving God selflessly and sacrificially is not easy, but it is worth it in the end.",
      "We should not serve God because of what we can get from Him; rather, we should serve Him selflessly.",
    ],
  },
  {
    slug: "2026-07-12-a-rewarding-service",
    dateIso: "2026-07-12",
    date: "July 12, 2026",
    minister: "Evangelist J.O. Durojaiye",
    theme: "Serving God to Attract Divine Favour",
    topic: "A Rewarding Service",
    texts: "Matthew 7:22–23; Acts 10:38; Exodus 23:23–31",
    excerpt: "You cannot serve a God you do not know. Serving Him is our calling, not an optional extra for the especially devoted.",
    body: [
      "You cannot serve a God you do not know. As children of God, serving Him is our calling — not an optional extra for the especially devoted, but the normal shape of a life that has met Him.",
      "Serving God has to do with our devotion to Him and our availability to Him. It must come out of love, not obligation, and it must be done with the right heart — because a service that will be rewarded by God is one done with the right heart, not merely the right hands.",
      "Serve God faithfully, sincerely, and wholeheartedly. Our service attracts God's attention, and one of the ways we position ourselves to attract His blessings is simply by serving Him (Exodus 23:23–31).",
    ],
  },
  {
    slug: "2026-08-02-confronting-your-giants",
    dateIso: "2026-08-02",
    date: "August 2, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Confronting Your Giants",
    texts: "1 Samuel 17:41; James 4:7; Psalm 18:32",
    podcastUrl: "https://open.spotify.com/episode/68vQ1zxIMWc5zzQwpVvDbG",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/confronting-your-giants/id1872275390?i=1000785631238",
    excerpt: "A giant can be seen as a spiritual terrorist sent by the devil to harass and torment the people of God. But giants are meant to be confronted, not endured.",
    body: [
      "A giant can be seen as a spiritual terrorist sent by the devil to harass and torment the people of God. Giants are real — and it helps to remember that, like Goliath, they are from the lineage of men. Whatever towers over your life right now is not beyond the reach of God.",
      "Giants are meant to be confronted, not negotiated with or quietly endured. The moment we become children of God, we are spiritually empowered to confront them — that power is not something we work up, but something we already carry.",
      "Giants can be conquered. The power given to you as a child of God is enough to enable you to conquer any giant, no matter how great it may be.",
    ],
  },
  {
    slug: "2026-08-16-how-to-calm-the-storm-of-life",
    dateIso: "2026-08-16",
    date: "August 16, 2026",
    minister: "Pastor D.O.B. Osundeyi",
    topic: "How to Calm the Storm of Life",
    texts: "Mark 4:35–41; Job 1:19; Genesis 19:24",
    excerpt: "Storms are a real part of human life — they do not respect status, and they can happen to anyone, at any time. But not every storm has the same source.",
    body: [
      "Storms are a real part of human life — something every one of us will encounter on the journey. They do not respect status, and they can happen to anyone, at any time.",
      "Not every storm has the same source. A storm can be a tool of the devil, set on destroying something in your life. It can also be a tool in God's own hand — to correct the disobedient, or to test and strengthen the faith of a believer. Knowing which storm you are in shapes how you pray through it.",
      "But whatever the source, one key overcomes them all: allowing God to be in the boat of your life. The disciples' storm on the Sea of Galilee was only ever a crisis because, for a moment, they forgot who was in the boat with them (Mark 4:35–41).",
    ],
  },
  {
    slug: "2026-08-30-the-unchanging-god",
    dateIso: "2026-08-30",
    date: "August 30, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "The Unchanging God",
    texts: "Jeremiah 31:3",
    podcastUrl: "https://open.spotify.com/episode/5qTbD7IAv0o3zJ6K3FRUfg",
    excerpt: "God is unchanging in His love — and that unchanging nature is one of the things that sets Him apart from man.",
    body: [
      "God is unchanging in His love — and that unchanging nature is one of the things that sets Him apart from man. People shift with circumstance; God does not.",
      "His love is unconditional. It is not based on who you are or what you can offer Him — there is no condition attached to being loved by God. It is also priceless: no amount of money could ever purchase what He gives freely and everlastingly (John 3:16).",
      "The level of the Word of God you know determines the amount of God you will enjoy. And one of the simplest ways to repay a love like this is through thanksgiving.",
    ],
  },
  {
    slug: "2026-09-06-dealing-with-anger",
    dateIso: "2026-09-06",
    date: "September 6, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Dealing with Anger",
    texts: "Ecclesiastes 7:9; Proverbs 14:17, 29; 1 Samuel 9:18",
    podcastUrl: "https://open.spotify.com/episode/05sccGbnpxx4N4okmm6nvo",
    applePodcastUrl: "https://podcasts.apple.com/us/podcast/dealing-with-anger/id1872275390?i=1000788179855",
    excerpt: "Anger is an emotion. God placed anger in man to show displeasure toward the things of the devil.",
    body: [
      "Anger is an emotion. God placed anger in man to show displeasure toward the things of the devil.",
      "Anger has to be dealt with, because anger itself is a destructive spirit.",
      "Anger has the power to destroy one's relationship with God.",
      "As children of God, we are not expected to act while we are angry.",
      "When anger takes control, it is impossible to act godly.",
    ],
  },
  {
    slug: "2026-09-13-standing-firm-in-the-faith",
    dateIso: "2026-09-13",
    date: "September 13, 2026",
    minister: "Pastor R.T. Owoseni",
    topic: "Standing Firm in the Faith",
    texts: "Proverbs 23:17–18; Colossians 1:27",
    excerpt: "To be fulfilled in life, it is important to stand firm in the faith.",
    body: [
      "To be fulfilled in life, it is important to stand firm in the faith.",
      "Faith is our spiritual anchor in the journey of life; it stabilizes us.",
      "Standing firm in the faith helps us not to envy sinners. The end of sinners is very terrible. As believers, we are meant to stand firm in the faith so as to avoid envying others.",
      "Standing firm in the faith guarantees our expectations.",
      "Standing firm in the faith gives us hope in Christ.",
      "One of the reasons to stand firm in the faith is the fact that there is an END.",
    ],
  },
];

// Newest first, for the listing page.
export const ILORIN_SERMONS_BY_DATE_DESC: IlorinSermon[] = [...ILORIN_SERMONS].sort(
  (a, b) => (a.dateIso < b.dateIso ? 1 : -1)
);

export function getIlorinSermon(slug: string): IlorinSermon | undefined {
  return ILORIN_SERMONS.find((s) => s.slug === slug);
}
